### ISSUE TITLE
Cluster crashes app

### ISSUE THREAD

**Issue by chitgoks** [HMS-Core/hms-mapkit-demo-java#1]
steps to reproduce

set huaweimap clustering to true
set markeroption as clusterable to true
set markeroption icon using bitmapdescriptorfactory.fromresource(r.drawable.anyresource)

then clear map.
then redo steps above.
notice crasj

**Comment by weizhenghms** [comment]
Hi chitgoks, this is a known issue that occurs in versions earlier than HMS 4.0.3. This problem has been resolved in Map4.0.4 version. 
The first way is to enable AppGallery -- Me --Settings --enable Auto-updata over Wi-Fi. If your phone is connected to a Wi-Fi network and has sufficient battery power, the map will be automatically updated in the early morning.
 Method 2: Open the Settings -- Apps -- Apps -- Huawei Services Framework -- Huawei Storage -- CLEAR DATA, and then open the map again. Two upgrade prompts are displayed. Select Update. After the update is complete, open the map again.

PS:
How to check map version:  we can search this key word in logs: get athUrl success.athUrl is
For example, I got this log: this means map version is 40004300

2020-06-09 14:37:14.449 24933-25023/com.huawei.hms.maps.demo I/HmsMapKit_AuthenticateClient_11246: get athUrl success.athUrl is https://map-dra.platform.hicloud.com/map/v2/license/authenticate?clientVersion=40004300

![image](https://user-images.githubusercontent.com/66658628/84114600-3ec60000-aa5f-11ea-800f-b94b11359477.png)
