### ISSUE TITLE
The image doesn't show up

### ISSUE THREAD

**Issue by fenrir-wangxin** [HMS-Core/hms-mapkit-demo-java#10]
Other functions are normal, but the map can't be displayed， The environment is in China
http://chuantu.xyz/t6/741/1603850381x-591238492.png
http://chuantu.xyz/t6/741/1603850438x1700340450.png

**Comment by lovehuaweimaps** [comment]
Please take a screenshot and upload your Android log. We'll help you find out why.

**Comment by fenrir-wangxin** [comment]
> Please take a screenshot and upload your Android log. We'll help you find out why.

I've worked it out, thanks
https://stackoverflow.com/questions/64465638/hms-map-kit-is-not-rendering
