### ISSUE TITLE
Huawei Map Kit does not load maps on virtual device.

### ISSUE THREAD

**Issue by halilozel1903** [HMS-Core/hms-mapkit-demo-java#9]
Hello,

I started using Huawei Map Kit. When I open the application on the Huawei Virtual device, the map is blank. What should I do?

<img width="323" alt="Screen Shot 2020-10-19 at 4 00 02 PM" src="https://user-images.githubusercontent.com/22895813/96454172-28f1f400-1224-11eb-84ed-96a1d2761f87.png">

Can you help me please?

**Comment by lovehuaweimaps** [comment]
Please check the log file. Check whether the map fails to be loaded due to authentication failure.

**Comment by halilozel1903** [comment]
I deleted the project and uploaded it again. I followed the steps involved but got the error below.

`2020-10-21 10:21:22 1917-2571/? W/AppInfoRecord: in host ower not found package:com.veripark.ykbaz
`

Can you help me?

**Comment by lovehuaweimaps** [comment]
Please take a screenshot and upload your Android log. We'll help you find out why.

**Comment by halilozel1903** [comment]
I don't understand. I added SHA-256 certificate fingerprint in Android App. Why this error?

![Screen Shot 2020-10-21 at 11 09 49 AM](https://user-images.githubusercontent.com/22895813/96691788-fe23af00-138d-11eb-8a4f-3e8acf67d3e5.png)

**Comment by lovehuaweimaps** [comment]
The error code is 010002,  your fingerprint certificate is invalid. Refer to the error code invalidolution and try again.
https://developer.huawei.com/consumer/en/doc/developmen
![010002errorcode](https://user-images.githubusercontent.com/60932689/96714928-76619300-13d5-11eb-9353-701a897321e5.png)
t/HMSCore-Guides-V5/faq-0000001050166999-V5

**Comment by lovehuaweimaps** [comment]
The error code is 010002, your fingerprint certificate is invalid. Refer to the error code invalidolution and try again.
https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides-V5/faq-0000001050166999-V5
![010002errorcode](https://user-images.githubusercontent.com/60932689/96715060-a6a93180-13d5-11eb-8381-b3447da0fe0c.png)

**Comment by halilozel1903** [comment]
Ok. 👍 My fault. 🤦‍♂️  I solved this problem ✅ Thanks 😊 

![image](https://user-images.githubusercontent.com/22895813/96723989-f37e0f80-13b7-11eb-8a34-372dedd7c523.png)

**Comment by lovehuaweimaps** [comment]
You're welcome. Welcome to Huawei Map.

**Comment by alkincakiralar1996** [comment]
how did you solve ?

**Comment by halilozel1903** [comment]
I had an error in the apk signing file. I solved it. @alkincakiralar1996
